// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xazzthomgbcrubbklxhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhhenp0aG9tZ2JjcnViYmtseGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NTcyNTAsImV4cCI6MjA2MjQzMzI1MH0.4H-x2kWnTpiYyY-IvLPPhacC1qz2hDjRDhBkgiOgO2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);